import { supabase } from '@/lib/supabase/client';
import type { OnboardingFormData } from '@/types/database';
import { calculateNutritionPlan } from '@/lib/nutrition/macro-calculator';

// ==========================================
// 1. INTERFACES
// ==========================================

export interface WorkoutProgram {
  program_name: string;
  program_overview: string;
  duration_weeks: number;
  weeks: Array<{
    week_number: number;
    focus: string;
    workouts: Array<{
      day: string;
      workout_name: string;
      exercises: Array<{
        exercise_name: string;
        sets: number;
        reps: string;
        rest_seconds: number;
        notes?: string;
      }>;
    }>;
  }>;
}

// ==========================================
// 2. MAIN GENERATOR FUNCTION
// ==========================================

export async function generateAndSaveProgram(
  formData: OnboardingFormData,
  userId: string
) {
  console.log('📱 Mobile: Starting AI Program Generation...');
  
  // 1. Calculate Nutrition
  const nutrition = calculateNutritionPlan(formData);

  // 2. Filter Database for Valid Exercises (The Menu)
  const userEquipment = formData.available_equipment || [];
  
  // Simple inclusion check
  const has = (keyword: string) => userEquipment.some(item => item.toLowerCase().includes(keyword));
  
  // Build allowed types list
  const allowedTypes = ['bodyweight']; 
  if (has('dumbbell')) allowedTypes.push('dumbbell');
  if (has('barbell')) allowedTypes.push('barbell');
  if (has('cable') || has('band')) allowedTypes.push('cable');
  if (has('gym') || has('commercial')) {
      allowedTypes.push('machine', 'cable', 'barbell', 'dumbbell', 'assisted');
  }

  // Fetch the "Menu" for the AI
  const { data: dbExercises } = await supabase
    .from('exercises')
    .select('id, name, equipment, primary_muscle') // ✅ Need ID for linking later
    .in('equipment', allowedTypes);

  if (!dbExercises || dbExercises.length === 0) {
    throw new Error("No exercises found for your equipment.");
  }

  // 3. Generate Program via AI
  const program = await generateAIProgram(formData, dbExercises);

  // 4. SAVE METADATA TO DATABASE
  console.log('💾 Saving Metadata to Supabase...');

  // A. Save Profile
  const { error: profileError } = await supabase
    .from('user_fitness_profiles')
    .upsert({
      user_id: userId,
      primary_goal: formData.primary_goal,
      experience_level: formData.training_experience,
      days_per_week: formData.available_days_per_week,
      session_duration: formData.session_duration, // ✅ Added duration
      equipment: formData.available_equipment,
      injuries: formData.current_injuries,
      onboarding_completed: true
    });

  if (profileError) throw new Error(`Profile Save Failed: ${profileError.message}`);

  // B. Save Nutrition
  await supabase.from('nutrition_plans').insert({
    user_id: userId,
    calories: nutrition.daily_calories,
    protein: nutrition.macros.protein_grams,
    carbs: nutrition.macros.carbs_grams,
    fat: nutrition.macros.fat_grams,
    active: true
  });

  // C. Save The "Master Plan" (For the Dashboard View)
  await supabase.from('ai_generated_programs').insert({
    user_id: userId,
    name: program.program_name,
    program_data: program,
    is_active: true
  });

  // ==========================================
  // 5. INSTANTIATE WEEK 1 (THE FIX)
  // ==========================================
  console.log('🏗️ Building Active Sessions for Week 1...');
  
  // We only generate the actual database rows for Week 1 to save space/time.
  // Future weeks would be generated by a "Next Week" button in the app.
  const firstWeek = program.weeks[0];

  for (const workout of firstWeek.workouts) {
    // 1. Create the Session Header
    const { data: session, error: sessionError } = await supabase
      .from('workout_sessions')
      .insert({
        user_id: userId,
        name: workout.workout_name,
        total_volume: 0
      })
      .select()
      .single();

    if (sessionError || !session) {
      console.error("Session Create Error", sessionError);
      continue;
    }

    // 2. Create the Sets (The exercises inside the workout)
    for (const ex of workout.exercises) {
      
      // ✅ SMART MATCHING: Find the ID from the "Menu" we fetched earlier
      // We explicitly look for the exercise the AI named.
      let dbExercise = dbExercises.find(e => 
        e.name.toLowerCase() === ex.exercise_name.toLowerCase()
      );

      // ⚠️ Fallback: If AI made a slight typo (e.g. "Bench Press" vs "Barbell Bench Press")
      if (!dbExercise) {
         dbExercise = dbExercises.find(e => 
            e.name.toLowerCase().includes(ex.exercise_name.toLowerCase()) || 
            ex.exercise_name.toLowerCase().includes(e.name.toLowerCase())
         );
      }

      if (dbExercise) {
        // Insert the rows that show up in the "Start Workout" screen
        await supabase.from('set_logs').insert({
          session_id: session.id,
          exercise_id: dbExercise.id,
          set_number: 1, // We just create one 'log entry' per exercise to start
          target_reps: parseInt(ex.reps) || 10,
          weight: 0,
          // You could loop here if you want to pre-create 3 rows for 3 sets
        });
      } else {
        console.warn(`⚠️ Could not find DB match for AI exercise: ${ex.exercise_name}`);
      }
    }
  }

  return { success: true };
}

// ==========================================
// 3. AI LOGIC
// ==========================================

async function generateAIProgram(formData: OnboardingFormData, validExercises: any[]): Promise<WorkoutProgram> {
  const apiKey = process.env.EXPO_PUBLIC_GROQ_API_KEY;
  if (!apiKey) throw new Error('Missing API Key');

  // Create a clean list of names for the AI to pick from
  const exerciseMenu = validExercises.map(e => `"${e.name}"`).join(', ');

  const prompt = `
    Create a 4-week workout program.
    User Profile:
    - Goal: ${formData.primary_goal}
    - Level: ${formData.training_experience}
    - Schedule: Exactly ${formData.available_days_per_week} days per week.
    - Session Length: ${formData.session_duration} minutes.
    
    STRICT RULES:
    1. Create exactly ${formData.available_days_per_week} unique workouts per week.
    2. ONLY use exercises from this list: [${exerciseMenu}].
    3. Do NOT invent exercise names. Use the exact names provided.
    4. Output valid JSON matching the schema.

    JSON Schema:
    {
      "program_name": "string",
      "program_overview": "string",
      "weeks": [
        {
          "week_number": 1,
          "workouts": [
            {
              "workout_name": "string",
              "day": "Monday",
              "exercises": [
                { "exercise_name": "Exact Name From List", "sets": 3, "reps": "8-12", "rest_seconds": 60 }
              ]
            }
          ]
        }
      ]
    }
  `;

  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: 'You are a fitness API. Output strictly valid JSON.' },
          { role: 'user', content: prompt }
        ],
        temperature: 0.1, // Low temp for stricter adherence to the list
        response_format: { type: 'json_object' }
      })
    });

    const data = await response.json();
    return JSON.parse(data.choices[0].message.content);
  } catch (e) {
    console.error("AI Error", e);
    // Fallback if AI fails
    return {
      program_name: "Basic Start",
      program_overview: "Fallback program",
      duration_weeks: 4,
      weeks: [{
        week_number: 1,
        focus: "General",
        workouts: [{
          day: "Monday",
          workout_name: "Full Body",
          exercises: []
        }]
      }]
    };
  }
}